name: Update requirements.txt

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pipreqs
        run: |
          pip install pipreqs

      - name: Update requirements.txt
        run: |
          pipreqs --force .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add requirements.txt
          git commit -m "Update requirements.txt automatically" || echo "No changes to commit"
          git push
